### ISSUE TITLE
UnhandledPromiseRejectionWarning is shown with exception KafkaJSNumberOfRetriesExceeded for connect()

### ISSUE THREAD

**Issue by gygabyte** [tulios/kafkajs#418] opened 2019-07-06 17:42 UTC
This only actually happens when there are multiple consumers trying to connect at the same time. This warning is not shown when there is only one consumer.

Also, it is only in the first connect() and Kafka is not available

```
{"level":"ERROR","timestamp":"2019-07-06T17:27:49.140Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 127.0.0.1:9092","retryCount":5,"retryTime":9178}
(node:13288) UnhandledPromiseRejectionWarning: KafkaJSNumberOfRetriesExceeded
  Caused by: KafkaJSConnectionError: Connection error: connect ECONNREFUSED 127.0.0.1:9092
    at Socket.onError (/Users/psilva/development/projects/manhattanportal/node_modules/kafkajs/src/network/connection.js:136:23)
    at Socket.emit (events.js:194:15)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:13288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Code for connecting:
```
this._consumer.connect()
                .then(r =>
                    this._consumer.subscribe({
                        fromBeginning: false,
                        topic: this._topic
                    }))
                .then(r => {
                    return this._consumer.run({
                        autoCommit: true,
                        autoCommitInterval: global.kafkaAutoCommitInterval,
                        autoCommitThreshold: global.kafkaAutoCommitThreshold,
                        eachMessage: (p) => {
                            try {
                                this.processMessage(p);
                            }
                            catch(e) {
                                   // log error
                            }
                            return Promise.resolve();
                        }
                    })
                })
                .catch(e => {
                    if(e.retriable === false) {
                        // consumer failed to connect and won't keep retrying
                        // perform shutdown and reconnect

                        setTimeoutPromise(global.kafkaConnectInterval).then(() => this._consumer.disconnect()).then(() => this.connect());
                    }

                    this.emit("error", e);
                });
        }
```

**Comment by IvanovOleg** [comment] 2019-07-22 08:20
I have the same issue.

**Comment by tulios** [comment] 2019-07-22 14:42
I will take a look at this now, @gygabyte @IvanovOleg how do you initialize your consumers? Do you have a `Promise.all` using the example code to connect?

**Comment by IvanovOleg** [comment] 2019-07-22 14:51
@tulios 
```
const consumer = this.kafka.consumer({
       groupId: ${this.options.groupIdPrefix}-${this.options.consumerGroup}-${uuid()},
       maxWaitTimeInMs: this.options.maxWaitTimeInMs,
       allowAutoTopicCreation: false
});
```

**Comment by Rolandisimo** [comment] 2019-07-25 09:53
I did some digging. I think the issue might be caused because of a forgotten `catch` block in `kafkajs/src/broker/index.js` file and `connect` method. Currently you have `try/finally`.  Adding an empty `catch` removed the uncaught exception related to retries, but revealed a new one.

```
(node:2619) UnhandledPromiseRejectionWarning: Error: Broker not connected
11:49:36 0|server  |     at Broker.lookupRequest (/Users/rolandjegorov/Dropbox/Work/Repos/toolkitv2/node_modules/kafkajs/src/broker/index.js:55:13)
11:49:36 0|server  |     at Broker.metadata (/Users/rolandjegorov/Dropbox/Work/Repos/toolkitv2/node_modules/kafkajs/src/broker/index.js:179:27)
11:49:36 0|server  |     at retrier (/Users/rolandjegorov/Dropbox/Work/Repos/toolkitv2/node_modules/kafkajs/src/cluster/brokerPool.js:123:38)
11:49:36 0|server  |     at retry (/Users/rolandjegorov/Dropbox/Work/Repos/toolkitv2/node_modules/kafkajs/src/retry/index.js:43:5)
11:49:36 0|server  |     at Promise (/Users/rolandjegorov/Dropbox/Work/Repos/toolkitv2/node_modules/kafkajs/src/retry/index.js:62:5)
11:49:36 0|server  |     at new Promise (<anonymous>)
11:49:36 0|server  |     at BrokerPool.fn [as retrier] (/Users/rolandjegorov/Dropbox/Work/Repos/toolkitv2/node_modules/kafkajs/src/retry/index.js:59:10)
11:49:36 0|server  |     at BrokerPool.refreshMetadata (/Users/rolandjegorov/Dropbox/Work/Repos/toolkitv2/node_modules/kafkajs/src/cluster/brokerPool.js:121:17)
11:49:36 0|server  |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by tulios** [comment] 2019-07-26 09:27
The broker is correct; it should propagate the error. The fix is probably higher up.

**Comment by tulios** [comment] 2019-07-26 09:30
@Rolandisimo how do you start your consumers, I am having a hard time reproducing this. I probably have the wrong setup, can you write a small script that reproduces the problem?

**Comment by Rolandisimo** [comment] 2019-07-27 11:08
@tulios I solved the issue. Actually, it was nothing more than an honest mistake on our side. All this time I thought it's  `consumer.connect` that causes the issue, whereas in reality it was an unhandled `consumer.subscribe`. I handled that and now everything is fine. Sorry for the confusion. 

Part of the reason for this mistake were old types that we had. We had a mix of custom types and types from `@types/kafkajs`. The latter is not maintained as far as I understand because `kafkajs` comes with types already.

Because of that, I also noticed that the last release for `kafkajs` was almost a month ago, but there were many commits to the master branch. At the very least release `1.9.3` has outdated types compared to the current master branch. Hence, I wanted to know this:

1. Are you planning to make a release anytime soon?
2. Why don't you release with every new commit? It is after all an addition/removal/change of functionality and/or behavior.  

Currently, I put direct link to the master branch in my package.json `kafkajs: "tulios/kafkajs"`

**Comment by Nevon** [comment] 2019-07-27 11:18
The reasoning behind our release strategy is documented here: https://kafka.js.org/docs/pre-releases

As of yesterday, we publish pre-release versions on every push to master, that you can install via the beta tag.

**Comment by Rolandisimo** [comment] 2019-07-27 11:29
@Nevon Thanks for pointing it out. Where can I find a list of exact pre-release versions?

**Comment by Nevon** [comment] 2019-07-27 11:51
You can find all versions through npm: https://www.npmjs.com/package/kafkajs?activeTab=versions

**Comment by Rolandisimo** [comment] 2019-07-27 12:40
Awesome! Thanks @Nevon and @tulios

**Comment by Rolandisimo** [comment] 2019-07-27 12:45
@gygabyte I think your issue is the same as mine i.e. you have `this.consumer.subscribe` that is unhandled and is throwing. Add a `.catch()` or return it in `then` so that the `catch` block of `this._consumer.connect` can handle the error

**Comment by tulios** [comment] 2019-08-01 07:52
Thanks @Rolandisimo, I am closing the issue. @gygabyte feel free to re-open it if you think it's not the same issue.

**Closed by tulios** 2019-08-01 07:52 UTC
Labels: Investigate

**Comment by gygabyte** [comment] 2019-08-19 16:28
sorry for the delay, but only had time now to look into this again.
I have refactored this code to catch all exceptions, but I am still seeing this issue. but again, only if I have multiple consumers trying to connect simultaneously.

also, this notation 
```
then(r =>
                    this._consumer.subscribe({
                        fromBeginning: false,
                        topic: this._topic
                    }))
```

is already returning the promise. the one liner lambda-like function implicitily returns the result. 

I believe it is not the same issue

**Comment by Rolandisimo** [comment] 2019-08-22 06:01
Try this @gygabyte and let me know if it works:
```
this._consumer.subscribe({
  fromBeginning: false,
  topic: this._topic
}).then(...).catch(...);
```

**Comment by gygabyte** [comment] 2019-08-22 10:16
@Rolandisimo this exception is occurring before subscribing.

I now have the connect step like this:

```
private connectClient(delay?: number) {
        let init;
        if (delay && delay >= 0) {
            init = setTimeoutPromise(delay);
        } else {
            init = Promise.resolve()
        }

        return init.then(() => this._consumer.connect())
            .then(r => logger.writeInfo("connectClient", `[${this._topic}] consumer connected`))
            .catch((e) => {
                if (!e.retriable) {
                    /// Kafka JS won't retry to connect any longer
                    logger.writeError("connectClient", `[${this._topic}] failed to connect consumer. retrying ${e}`);
                    return this._consumer.disconnect().then(() => this.connectClient(global.kafkaConnectInterval));
                }

                /// unable to connect
                return Promise.reject(e);
            })
    }
```

and I am still getting the same exception I reported, but only for one of them. and again, this only occurs if I have multiple consumers trying to connect.

I also the subscribe step now implemented the same way as it wasn't recovering if the topic didn't exist. 
I have in fact uncovered a couple defects doing some chaos testing that I will be opening soon.

**Comment by Rolandisimo** [comment] 2019-08-22 12:40
I can't be sure about the whole repository you have, but from the code example above, I'd say it's because of `this._consumer.connect()` not having a `then.catch`. In fact, I'd try to add `then().catch()` to every async operation you do and see at what point the issue is solved.

**Comment by gygabyte** [comment] 2019-08-22 16:03
@Rolandisimo I've already tried that, same result as expected.

Node.js promises don't require the .catch to be like that. As long as there is a .catch on the chain, the exception will be caught.

The code I have there, I am returning the Promise from connect and pass it down the chain. Then there is a .catch issuing a retry if the Promise is rejected.

The issue here, the Promise is correctly rejected, but there is some exception inside kafkajs not being handled. However, as I have stated, this only happens when multiple consumers are trying to connect and just of the consumers hits this warning.

This is not a biggie as Node.js happily reports it for now, but as the message says, it will get the process killed in future versions

**Comment by Rolandisimo** [comment] 2019-08-22 21:57
@gygabyte Do you think you could make a small demo repo with this issue? I believe that would also help the contributors

**Comment by tulios** [comment] 2019-08-23 07:32
@gygabyte a small demo would help us a lot, and I had a hard time reproducing this issue. We have a lot of projects using multiple consumers in production, and we can't see the issue there.

**Comment by bluEEil** [comment] 2021-06-29 13:29
I suspect I might have a similar problem, I get the error:
```
Broker not connected
    at Broker.lookupRequest (/north/hq_north_bridge/node_modules/kafkajs/src/broker/index.js:65:13)
    at Broker.metadata (/north/hq_north_bridge/node_modules/kafkajs/src/broker/index.js:189:27)
    at /north/hq_north_bridge/node_modules/kafkajs/src/cluster/brokerPool.js:155:38
    at retry (/north/hq_north_bridge/node_modules/kafkajs/src/retry/index.js:43:5)
    at /north/hq_north_bridge/node_modules/kafkajs/src/retry/index.js:61:5
```
This happens in some tests I run in my CI/CD. It happens only sometimes and it occurs to different test (which connect to kafka using KafkaJS). It's all pretty random and I can't figure out why it happens and how to prevent it. 
What I do is connect to Kafka, connect with a Producer and Admin, create a topic, and then publish a message to this topic (doing all of this to check that the connection works). I didn't manage to understand from the error call stack where specifically the problem occurs. I'm pretty clueless about how to solve this at this point so would appreciate any ideas.
