### ISSUE TITLE
kafka.Admin is not a function

### ISSUE THREAD

**Issue by valavanisleonidas** [tulios/kafkajs#991] opened 2020-12-29 12:38 UTC
**Describe the bug**
I try to use the admin from kafka.admin() and it produces the error 'kafka.admin is not a function '

**To Reproduce**
Please provide either a link to a:
just using the following commands is enough

const kafka = new Kafka({
  clientId: config.clientId,
  brokers: config.brokers,
  connectionTimeout: config.connectionTimeout,
  authenticationTimeout: config.authenticationTimeout,
  reauthenticationThreshold: config.reauthenticationThreshold,
});

const admin = kafka.admin();

**Environment:**
 - OS: [Mac OS 11.0.1]
 - KafkaJS version [1.15.0]
 - Kafka version [2.12-2.3.0]
 - NodeJS version [10.16.3]

**Comment by Nevon** [comment] 2020-12-29 13:41
Duplicate of #990

**Closed by Nevon** 2020-12-29 13:41 UTC
