### ISSUE TITLE
Corrupted Offset when using eachBatch

### ISSUE THREAD

**Issue by chrflo** [tulios/kafkajs#1212] opened 2021-10-21 06:32 UTC
**Description**
About a month ago, we switched from using eachMessage to eachBatch and recently noticed that our services' consumers were not processing events from random partitions. There have been no issues observed with the producers, and the issue just started occurring after about a month of working fine with no changes to our config or consume method. The only change that occurred was on our infrastructure side, where we enabled capture on the event hub; however, it's not evident how that could cause this issue. Upon further investigation, we noticed that the offset somehow gets corrupted and is no longer at the position that it should be. Effectively, the consumers stop reading messages as it doesn't appear that there are any messages to read. We reset the offset to latest, which resolved the issue for a period of time; however, it returned (again randomly) an hour or two later. It is worth mentioning that reverting back to processing using eachMessage prevents this corruption of the offset and that in both instances we are using manual commits.

I have included the config and an example implementation below. Really appreciate any help with this.

**Config**

```ts
this.allowAutoTopicCreation = false;
this.autoCommit = false;
this.autoCommitThreshold = 1;
this.consumerRetryOptions = {
  retries: 2,
  factor: 2,
  minTimeout: 2000,
  maxTimeout: 10000,
  randomize: true,
};
this.continueOnFailedEventProcessing = false;
this.eachBatchAutoResolve = false;
this.heartbeatInterval = undefined;
this.maxSleepCycles = 1;
this.partitionsConsumedConcurrently = 8;
this.recoveryPosition = false;
```

**Example Implementation** 

```ts
public async consume () => {
  await this.client.run({
    eachBatchAutoResolve: false,
    autoCommitThreshold: 1,
    partitionsConsumedConcurrently: 8,
    eachBatch: async ({
      batch,
      resolveOffset,
      heartbeat,
      commitOffsetsIfNecessary,
    }) => {
      /* logic to prevent concurrent event processing on the same partition. */

      for (const message of batch.messages) {
        let event: Event<any>;
        const partitionKey = message.key ? message.key.toString() : message.key;
        const { offset, timestamp } = message;
        const context: EventContext = {
          topic,
          partition,
          partitionKey,
          offset,
          timestamp,
        };
        
        try {
          // transform kafka message to custome event
          event = await this.transform(message);
        } catch (error) {
          try {
            resolveOffset(offset);
            await heartbeat();
            await commitOffsetsIfNecessary();
          } catch (commitError) {
            	/* signal and await shutdown */
          }
          break;
        }
        
        try {
          /* process event with custom handler and retry logic */
          
	  resolveOffset(offset);
          await commitOffsetsIfNecessary();
          await heartbeat();
        } catch (error) {
          
      }
      this.partitionTracker.stopProcessing(partitionId);
      await this.shutdownCheck();
    },
  });
};
```

**Environment**:
OS: Mac OS 11.2.3
KafkaJS Version: 1.14.0
Platform: Microsoft Event Hubs
NodeJS Version: 12.x

**Comment by nt-ijlizarralde** [comment] 2021-12-02 12:39
Hi, MSFT created a fix for this. Here you have the explanation.

As part of the service upgrade, a change was introduced to address a problem with regard to slow partition fetch for empty partition. However as part of the optimization, a changed behaviour is introduced. Specifically, normally, when client fetch for an offset that is in the future (i.e. one that exceeded the last known offset) the fetch call should return empty records. The changed behaviour caused a race condition, where in specific sequence, the last event will be returned instead of empty record.
 
The condition by itself, even though is undesirable, does not cause a permanent stuck condition, because normally a client would have ignored the redundant event, and ask for the same offset again, and eventually, the future offset will become current (because producer keep on sending events). However it looks like KafkaJS library has a specific behaviour where it does not detect that the event returned are in the past, and the client side in-memory offset just keep on incrementing (i.e. it blindly assume that if there are non-empty records, that records must have the offset that it asked for). This condition caused a permanent stuck issue under the right condition, because no matter how many events producer sends, the client will just keep on incrementing and asking for a larger and larger offset. This condition can only get resolved by restarting the client, wiping the in memory state of the offset and start from fresh.
 
The changed behaviour has been reverted for all public cluster, and the fix for the original problem will be fixed in such a way that will not cause further regression. Additional work items are planned to increase coverage for KafkaJS library to avoid hitting regression again in that category of external libraries.

**Comment by chrflo** [comment] 2021-12-13 05:18
@nt-ijlizarralde thanks so much for letting me know - much more detail than we have gotten from MSFT

**Comment by Nevon** [comment] 2021-12-13 08:54
I'm going to close this issue as it's an issue in Event Hubs that has now been fixed, but I would still be interested in how exactly to reproduce this. From reading the description, it sounds like we should already handle this, but clearly we didn't.

https://github.com/tulios/kafkajs/blob/e3c6d91b7b54594db64e568afc61c0a857bbd54b/src/consumer/__tests__/batch.spec.js#L6-L22

Maybe I'm misunderstanding the behavior, or maybe there's something else in the client that causes this. Either way, I'd be interested in understanding it better.

**Closed by Nevon** 2021-12-13 08:54 UTC

**Comment by nt-ijlizarralde** [comment] 2021-12-16 15:51
@Nevon 

We didn't have this issue with Java Libraries only with KafkaJS. And we still have the issue with other tenants of Node.

MSFT commented the following. I understand that something in KafkaJS can be done to prevent this.  I think KafkaJS could think in adding and enhancement to make sure it works well with Azure Event Hubs. 

_However it looks like KafkaJS library has a specific behaviour where it does not detect that the event returned are in the past, and the client side in-memory offset just keep on incrementing (i.e. it blindly assume that if there are non-empty records, that records must have the offset that it asked for). 
.... Additional work items are planned to increase coverage for KafkaJS library to avoid hitting regression again in that category of external libraries._

**Comment by Nevon** [comment] 2021-12-17 12:16
> I understand that something in KafkaJS can be done to prevent this. I think KafkaJS could think in adding and enhancement to make sure it works well with Azure Event Hubs

Yeah, I wouldn't mind that, but based on the description of the issue, we should already handle this case according to the test I linked above. So either the description of the error is wrong, my interpretation of it is wrong, or our handling of that case is insufficient, but I can't tell which without more information or a way to reproduce the issue.
