### ISSUE TITLE
Does KafkaJS support Static Membership?

### ISSUE THREAD

**Issue by SandraShklyaeva** [tulios/kafkajs#1242] opened 2021-11-29 15:36 UTC
Does KafkaJS support Kafka Static Membership? I see in the docs the module supports Kafka 0.10+ and the static membership is introduced in Kafka 2.3. But I can't find related config for the consumer to pass consumer instance id (group.instance.id) to use static membership.

**Comment by tobalsgithub** [comment] 2021-12-07 20:25
@SandraShklyaeva I've been digging through the code a bit and I think the answer is "No", kafkajs does not support this yet. [Here's](https://github.com/tulios/kafkajs/issues/638) another closed issue where the feature was discussed briefly. That issue also links to a fork where someone else implemented the `group.instance.id` property to allow for static membership. 

Figured I'd share my findings in case they're helpful. 

I'd love to see this feature as it would help with rebalances significantly.

**Comment by mksmtn** [comment] 2022-05-01 14:36
possible duplicate of #884

**Comment by Nevon** [comment] 2022-05-02 05:37
Closing as duplicate of #884.

**Closed by Nevon** 2022-05-02 05:37 UTC
