### ISSUE TITLE
Connection stuck if first broker on the list is down

### ISSUE THREAD

**Issue by itayadler** [tulios/kafkajs#368] opened 2019-05-22 08:59 UTC
**Issue**:
`let config = { brokers: ['broker1:9092', 'broker2:9092', 'broker3:9092'] }`
assuming `broker1:9092` is down, kafkajs will fail to connect to the cluster. But if the order
is :
`let config = { brokers: ['broker2:9092', 'broker1:9092', 'broker3:9092'] }`
or
`let config = { brokers: ['broker3:9092', 'broker2:9092', 'broker1:9092'] }`
The connection will work fine.

I'd expect kafkajs to be able to connect to the cluster in case one broker is down, and that broker is the first on the list, WDYT?

**Comment by itayadler** [comment] 2019-05-22 09:13
Update: it seems that it does manage to connect https://github.com/tulios/kafkajs/blob/master/src/broker/index.js#L79 but it get stuck on this call https://github.com/tulios/kafkajs/blob/master/src/broker/index.js#L82
which is related to the issue I currently have with this broker, so perhaps adding a timeout to this call will make the client more robust to this edge case

**Comment by tulios** [comment] 2019-05-22 12:45
Right, we should enforce a timeout for the API versions call.
Thanks for investigation

**Comment by itayadler** [comment] 2019-05-22 12:53
I can try to make a PR to enhance this, do you have a rough example of how you'd like it to act?

**Comment by tulios** [comment] 2019-05-22 12:58
You can pass a request timeout to any request
https://github.com/tulios/kafkajs/blob/326403fb096a097e821e03a5c780bb6e73064ba9/src/network/connection.js#L252

make `apiVersions` accept an optional `requestTimeout`
https://github.com/tulios/kafkajs/blob/326403fb096a097e821e03a5c780bb6e73064ba9/src/broker/index.js#L130

then always pass the `connectionTimeout` to `apiVersions` in the `connect` method
https://github.com/tulios/kafkajs/blob/326403fb096a097e821e03a5c780bb6e73064ba9/src/broker/index.js#L82

I am thinking about using the `connectionTimeout` because this is a fast request and it is part of the connection flow, WDYT?

**Comment by itayadler** [comment] 2019-05-22 13:09
sounds good, let me have a go at it

**Comment by itayadler** [comment] 2019-05-22 14:34
https://github.com/tulios/kafkajs/pull/369

**Comment by vykimo** [comment] 2019-05-28 16:42
Confirmed my side

**Comment by tulios** [comment] 2019-06-06 17:33
Fixed by #369

**Closed by tulios** 2019-06-06 17:33 UTC
Labels: enhancement
