### ISSUE TITLE
 don't understand the behavior of committing

### ISSUE THREAD

**Issue by yuriabaev** [tulios/kafkajs#774] opened 2020-06-23 10:10 UTC
I have this log that I print when consuming messages, where i send messages (which are numbers, from 1 to 6)
I run the consumer  with `autoCommitThreshold: 5` configuration

but I don't understand the behavior of committing:
why the CG offset jumped from 198 to 199 and after 3  (not 5!) messages (messages 2,3,4) it jumped to 202 
I would expect it commit  only after5 messages , not 3

why does this happen?

in the log I print:
-the message received 
-topic offsets of the
-customer group offset

```
topic 12:39:50:81 {"topicOffset":[{"partition":0,"offset":"198","high":"198","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"198","metadata":null}]}
topic 12:39:51:92 {"topicOffset":[{"partition":0,"offset":"198","high":"198","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"198","metadata":null}]}
recieved message { partition: 0, offset: '198', value: '1' }
topic 12:39:52:91 {"topicOffset":[{"partition":0,"offset":"199","high":"199","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"198","metadata":null}]}
topic 12:39:53:93 {"topicOffset":[{"partition":0,"offset":"199","high":"199","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"198","metadata":null}]}
topic 12:39:54:98 {"topicOffset":[{"partition":0,"offset":"199","high":"199","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"198","metadata":null}]}
topic 12:39:55:102 {"topicOffset":[{"partition":0,"offset":"199","high":"199","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"198","metadata":null}]}
topic 12:39:56:107 {"topicOffset":[{"partition":0,"offset":"202","high":"202","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"198","metadata":null}]}
done processing 1
recieved message { partition: 0, offset: '199', value: '2' }
topic 12:39:57:110 {"topicOffset":[{"partition":0,"offset":"205","high":"205","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
topic 12:39:58:113 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
topic 12:39:59:119 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
topic 12:40:0:124 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
topic 12:40:1:126 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
done processing 2
recieved message { partition: 0, offset: '200', value: '3' }
topic 12:40:2:127 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
topic 12:40:3:134 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
topic 12:40:4:138 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
topic 12:40:5:146 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
topic 12:40:6:147 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
done processing 3
recieved message { partition: 0, offset: '201', value: '4' }
topic 12:40:7:151 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
topic 12:40:8:157 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
topic 12:40:9:161 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
topic 12:40:10:163 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
topic 12:40:11:169 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"199","metadata":null}]}
done processing 4
recieved message { partition: 0, offset: '202', value: '5' }
topic 12:40:12:172 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"202","metadata":null}]}
topic 12:40:13:178 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"202","metadata":null}]}
topic 12:40:14:181 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"202","metadata":null}]}
topic 12:40:15:186 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"202","metadata":null}]}
topic 12:40:16:187 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"202","metadata":null}]}
done processing 5
recieved message { partition: 0, offset: '203', value: '6' }
topic 12:40:17:189 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"202","metadata":null}]}
topic 12:40:18:192 {"topicOffset":[{"partition":0,"offset":"207","high":"207","low":"0"}],"custonerGroupOffset":[{"partition":0,"offset":"202","metadata":null}]}
```

**Comment by Nevon** [comment] 2020-08-14 15:44
I believe this is a duplicate of #759

**Closed by Nevon** 2020-08-14 15:44 UTC
