### ISSUE TITLE
support other assigners, especially CooperativeStickyAssignor

### ISSUE THREAD

**Issue by DanielYWoo** [tulios/kafkajs#1156] opened 2021-07-26 12:53 UTC
**Is your feature request related to a problem? Please describe.**
CooperativeStickyAssignor provides 2 phase operations with minimum assignment changes. This is very important for continuous and robust service.

**Describe the solution you'd like**
Support CooperativeStickyAssignor.

**Additional context**
https://www.confluent.io/blog/cooperative-rebalancing-in-kafka-streams-consumer-ksqldb/

**Comment by tulios** [comment] 2021-07-26 14:04
We intend to work on this after our summer vacations.

**Comment by JordanPawlett** [comment] 2021-07-26 16:26
Came here looking for the same thing!

**Comment by Nevon** [comment] 2022-03-09 12:33
Closing as a duplicate of #922.

**Closed by Nevon** 2022-03-09 12:33 UTC
