### ISSUE TITLE
Connections with high latency result in a "Failed to connect to seed broker", "Connection Timeout"

### ISSUE THREAD

**Issue by ShawnUCD** [tulios/kafkajs#831] opened 2020-08-04 23:03 UTC
**Describe the bug**
All of our offshore users (located throughout India) are having the same issue starting their application.  When doing so, they receive messages such as the following:

`{"level":"ERROR","timestamp":"2020-08-04T22:08:43.164Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"b-3.removed.kafka.us-west-2.amazonaws.com:9094","clientId":"ip-192-168-1-132.us-west-2.compute.internal"}
{"level":"ERROR","timestamp":"2020-08-04T22:08:43.166Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":0,"retryTime":260}
{"level":"ERROR","timestamp":"2020-08-04T22:08:44.433Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"b-1.removed.kafka.us-west-2.amazonaws.com:9094","clientId":"ip-192-168-1-132.us-west-2.compute.internal"}
{"level":"ERROR","timestamp":"2020-08-04T22:08:44.434Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":1,"retryTime":582}
{"level":"ERROR","timestamp":"2020-08-04T22:08:46.019Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"b-2.removed.kafka.us-west-2.amazonaws.com:9094","clientId":"ip-192-168-1-132.us-west-2.compute.internal"}
{"level":"ERROR","timestamp":"2020-08-04T22:08:46.020Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":2,"retryTime":1386}
{"level":"ERROR","timestamp":"2020-08-04T22:08:48.415Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"b-3.removed.kafka.us-west-2.amazonaws.com:9094","clientId":"ip-192-168-1-132.us-west-2.compute.internal"}
{"level":"ERROR","timestamp":"2020-08-04T22:08:48.416Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":3,"retryTime":3060}
{"level":"ERROR","timestamp":"2020-08-04T22:08:52.484Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"b-1.removed.kafka.us-west-2.amazonaws.com:9094","clientId":"ip-192-168-1-132.us-west-2.compute.internal"}
{"level":"ERROR","timestamp":"2020-08-04T22:08:52.485Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":4,"retryTime":6746}`

To my knowledge, all of these users are running MacOS Catalina.  Running the same application locally allows me to connect without issue:

`{"level":"INFO","timestamp":"2020-08-04T22:33:51.717Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"shawn"}
{"level":"INFO","timestamp":"2020-08-04T22:33:55.017Z","logger":"kafkajs","message":"[Runner] Consumer has joined the group","groupId":"shawn","memberId":"ip-192-168-1-132.us-west-2.compute.internal-a37c7ce3-b4f3-4660-bdbb-8a918fe5b084","leaderId":"ip-192-168-1-132.us-west-2.compute.internal-a37c7ce3-b4f3-4660-bdbb-8a918fe5b084","isLeader":true,"memberAssignment":{"app1.sub":[0,1,2],"app2.sub":[0,1,2],"app1.sub":[0,1,2],"app1.sub2":[0,1,2]},"groupProtocol":"RoundRobinAssigner","duration":3299}`

**To Reproduce**
Using [Network Link Conditioner](https://nshipster.com/network-link-conditioner/), I have increased my latency to around what the end users are seeing (~300ms), and I see the exact same problem on starting my application.  Turning this off and returning to my normal latency (~30ms), I can connect without incident.

**Expected behavior**
User should be able to start app and receive message indicating that they joined the group successfully.

**Observed behavior**
When user with high latency attempts to connect to the broker, they are unable to do so, receiving Connection Timeout error.  

**Troubleshooting Steps**
I have adjusted the following values in our connect string:
authenticationTimeout (bumped to 10000)
connectionTimeout (increased to 5000)
requestTimeout (increased to 10000)

**Environment:**
 - OS: Mac OS 10.15.5
 - KafkaJS version 1.12.0
 - Kafka version 2.4.1 (AWS MSK)
 - NodeJS version 12.12.0

**Comment by goriunov** [comment] 2020-08-05 04:06
I am not sure that kafka is a good idea for this things... I would personally have an api with WebSocket to which different clients can connect and consume messages/data from as that one was designed for that kinda stuff. I personally don't think you can do much with above except only create kafka cluster somewhere near in that region  and make sure you have good internet between clients and kafka cluster...

**Comment by ShawnUCD** [comment] 2020-08-05 04:08
> I am not sure that kafka is a good idea for this things... I would personally have an api with WebSocket to which different clients can connect and consume messages/data from as that one was designed for that kinda stuff. I personally don't think you can do much with above except only create kafka cluster somewhere near in that region and make sure you have good internet between clients and kafka cluster...

Thanks Goriunov,
That's plan B, but I was hoping there might be some other solution.  Kafkacat connects without any problem.  The remote users are used to putting up with slower response while working on our applications, but there don't seem to be any available options other than what I've already tried.

**Comment by ShawnUCD** [comment] 2020-08-05 14:18
As I read through this I realize that I was unclear as to who exactly is affected by this issue.  These users are actually developers, working for us to develop our applications.  These users run the apps locally, but the Kafka cluster they're hitting exists in the US.  Our actual end users are not seeing these slowdowns, as the applications, databases, and Kafka cluster are all within close proximity to one another.

**Comment by goriunov** [comment] 2020-08-08 09:17
I don't think there is much you can do. May try tweaking timeouts.... Other solution is to create another cluster near to those devs and replicate between 2 different clusters

**Comment by Nevon** [comment] 2020-08-14 12:36
Sadly, network latency is what it is. The only thing you can really do in this case is to increase the timeouts.

However, it doesn't make sense that you're getting connection timeouts if you have set the connection timeout to 5000ms if your latency is ~300ms. 

There are two ways the connection timeout can happen. Before we connect, we start a `setTimeout` that will trigger the connection timeout error if it is not cleared (which it is after a successful connection):

https://github.com/tulios/kafkajs/blob/2882ef0ececb701c1eeda5b90d8458c43583cdea/src/network/connection.js#L173-L194

The other is if [the socket itself times out](https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback):

https://github.com/tulios/kafkajs/blob/2882ef0ececb701c1eeda5b90d8458c43583cdea/src/network/socket.js#L17

But by default there is no timeout on sockets, so this shouldn't trigger unless [you have a custom `socketFactory`](https://kafka.js.org/docs/configuration#custom-socket-factory) with a timeout set.

**Comment by Nevon** [comment] 2020-10-05 17:10
I'm going to close this since there's not much more we can do. Feel free to re-open the issue if you feel there is more information to add.

**Closed by Nevon** 2020-10-05 17:10 UTC
