### ISSUE TITLE
Incompatable protocol issue 

### ISSUE THREAD

**Issue by LakhsmiC** [tulios/kafkajs#463] opened 2019-08-12 15:58 UTC
Hello Team , i am unable to connect to consumer groups from Java . Is there any incompatable issue with Java? 
I am seeing this issue when i first connect to the consumer group with Nodejs client and then if some one uses the same consumer group and conencts with Java we are seeing these issues. I a way 1 consumer group is unable to consume from 2 different clients Java and Nodejs at the same time. I get below error :

2019-05-29 22:25:44,889 ERROR o.a.k.c.c.i.AbstractCoordinator: Attempt to join group xxxx.xxxx.xxxx failed due to fatal error: The group member's supported protocols are incompatible with those of existing members.
2019-05-29 22:25:44,889 ERROR o.a.j.p.j.s.JSR223Sampler: Problem in JSR223 script JSR223 Sampler, message: javax.script.ScriptException: org.apache.kafka.common.errors.InconsistentGroupProtocolException: The group member's supported protocols are incompatible with those of existing members.
javax.script.ScriptException: org.apache.kafka.common.errors.InconsistentGroupProtocolException: The group member's supported protocols are incompatible with those of existing members.
at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:320) ~[groovy-all-2.4.13.jar:2.4.13]

**Comment by JaapRood** [comment] 2019-08-12 16:31
I'm not sure which protocols KafkaJS doesn't support (@tulios will) that the Java consumer does, but just more overall seen can't imagine it's a wise idea of have clients from 2 different sources join the same consumer group.

_ConsumerGroup_s are meant as a way to split up the processing of certain topics between multiple nodes, assigning a bunch of partitions to each one. It's for the coordination of concurrently applying the same process and being able to scale your compute horizontally. AFAIK it's totally expected for these consumer in the group to be running from identical source, all doing the same thing, just for different partitions. I have a hard time imaging where doing anything else would be a good idea.

Given all that, I'd recommend running these 2 clients in their own ConsumerGroups, which should make your problem go away as well :) The two groups can process the same topics, completely individually from each other.

**Comment by Nevon** [comment] 2019-08-12 16:32
First: I've never heard of someone joining the same consumer group with consumers implemented in different languages, though. It sounds _extremely_ unusual to me. Theoretically it should be possible to have members in different languages, but I don't see any reason why you would want to.

--

Now, to the actual issue.

Whenever a new member joins a group, it needs to support the same assigner protocol (Java calls this the GroupProtocol) as the other members (or at least they all need to have one protocol in common, in case they support several).

The default assigner in the Java Kafka client is the [`RoundRobinAssignor`](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/RoundRobinAssignor.java). Similarly, KafkaJS' default is the [`RoundRobinAssigner`](https://github.com/tulios/kafkajs/blob/master/src/consumer/assigners/roundRobinAssigner/index.js).

I don't know off the top of my head if they are actually compatible, but at least their names are different. The Java one calls itself [`roundrobin`](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/RoundRobinAssignor.java#L139-L141) and we call ours [`RoundRobinAssigner`](https://github.com/tulios/kafkajs/blob/master/src/consumer/assigners/roundRobinAssigner/index.js#L9).

So, to fix this, we would need to:

1. Verify that our implementation and theirs _actually_ matches in behavior.
2. Create a Java compatible version of our `RoundRobinAssigner` that we call the same thing as theirs (`roundrobin`) so that Kafka can recognize that they are the same.

As a workaround, you can pass in a [custom `partitionAssigner` to the Consumer constructor](https://kafka.js.org/docs/consuming#a-name-options-a-options). You could copy our `RoundRobinAssigner` and just change the name to `roundrobin`. I believe that should be enough to allow your Java members to join the group - however, **I cannot guarantee that our implementation works the same as the Java one, which is needed for it to _actually_ work.** You would need to verify this first.

**Comment by rajjagani021** [comment] 2019-11-15 08:52
Hello @Nevon , I am getting the same error as above

`{"level":"ERROR","timestamp":"2019-11-15T08:25:32.552Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSProtocolError: The group member's supported protocols are incompatible with those of existing members","groupId":"dev_gsuite_consumer","stack":"KafkaJSProtocolError: The group member's supported protocols are incompatible with those of existing members\n    at createErrorFromCode (/Applications/MAMP/htdocs/7Span/sequr/demo/sequr-kafka-poc/kafka_js/node_modules/kafkajs/src/protocol/error.js:536:10)\n    at Object.parse (/Applications/MAMP/htdocs/7Span/sequr/demo/sequr-kafka-poc/kafka_js/node_modules/kafkajs/src/protocol/requests/joinGroup/v0/response.js:37:11)\n    at Connection.send (/Applications/MAMP/htdocs/7Span/sequr/demo/sequr-kafka-poc/kafka_js/node_modules/kafkajs/src/network/connection.js:306:35)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
`

I have produced the message successfully but when I am going to consume it I can't connect with the consumer and it throws the protocol error. Previously I was using the `node-rdkafk` and that also defaults using the `RoundRobinAssigner`.

**Comment by Nevon** [comment] 2019-11-15 09:27
> Previously I was using the node-rdkafk and that also defaults using the RoundRobinAssigner.

I believe that the rdkafka assigner is actually called `roundrobin`, same as the Java one. I haven't verified if it actually behaves exactly the same, but [it does reference the Java one](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_roundrobin_assignor.c), so I would guess so. Ours is called `RoundRobinAssigner`, not `roundrobin`, which is why it is conflicting. As mentioned above, I cannot guarantee that it behaves the same as the Java one. 

Have you tried the workaround I mentioned above?

**Comment by rajjagani021** [comment] 2019-11-15 10:10
Yes, I have tried that solution. As you can see in the attached screenshot and after that it might be solved that group protocol error but It can't connect with the broker. I am getting a timeout error after consumers joined with the group.  Do I missing something to change?
![connection_timeout](https://user-images.githubusercontent.com/4434991/68935205-3efa6780-07be-11ea-9c7b-f5982b09c031.png)
![round_robin](https://user-images.githubusercontent.com/4434991/68935206-3efa6780-07be-11ea-9f6d-73c65e9eec02.png)

**Comment by tulios** [comment] 2020-09-29 22:35
This seems like a network issue now; I am closing the issue but feel free to re-open if your problem is not solved.

**Closed by tulios** 2020-09-29 22:35 UTC
Labels: question

**Comment by ParhamZare** [comment] 2021-01-02 07:52
Hi, I faced this issue and I think this issue is related to the group Id of the consumer which you passed the same group id and the broker cant accepts the same group id. 

https://issues.apache.org/jira/browse/KAFKA-3829

**Comment by detro** [comment] 2024-05-01 07:29
@ParhamZare sorry, but I think https://issues.apache.org/jira/browse/KAFKA-3829 was an issue for which a fix was released in Kafka `0.10.2`. That was, around 2017 I believe. 

This issue is entirely caused by what @Nevon explained above: the `partition.assignor.strategy` names in KafkaJS are purposely mismatching the ones used in the Java "official" client and LibRDKafka too. Because work to make fully compatible assignors wasn't done.
