### ISSUE TITLE
Consumers are incrementally committing out of range offsets indefinitely

### ISSUE THREAD

**Issue by prabhakaran-motorq** [tulios/kafkajs#1217] opened 2021-10-23 04:33 UTC
**Describe the bug**
The consumer group is continuously incrementing the committed offsets greater than topic's last enqueued offset.
Lets assume a topic has only one partition with last enqueued offset as 2 and consumer group with committed offset as 2. During consumption, the consumer group is committing 3, then 4, then 5, like this indefinitely even though the topic's last offset is still 2.
This causes dataloss, when producer produces a message of offset 3 (or anything less than committed offset), it won't be consumed by the consumer group.

This issue is not occurring when Java Kafka consumer is used.

**To Reproduce**
1. Create Azure Eventhub Namespace. Create an eventhub with one partition and one day retention.
2. Push 1 message at T and another message at T + 60 mins.
3. Once the first message is evicted due to the retention period, push one more message. (So far 3 messages are pushed and 2 messages are available to consume). Do not push any more messages after this.
4. Try to consume with the following implementation
```typescript
import { Kafka, logLevel } from 'kafkajs';

const config = {
    BROKER: '', // eventhubnamespace:9093
    TOPIC: '', // eventhub name
    GROUP: '' // can be anything
}
const kafka = new Kafka({
    clientId: 'consumer',
    brokers: [config.BROKER],
    logLevel: logLevel.INFO,
    ssl: true,
    sasl: {
        mechanism: 'plain',
        username: '$ConnectionString',
        password: '', // Connection string from eventhub namespace
    },
});
const consumer = kafka.consumer({ groupId: config.GROUP });
const run = async () => {
    await consumer.connect();
    await consumer.subscribe({ topic: config.TOPIC });
    await consumer.run({
        eachMessage: async ({ partition, message }) => {
            const prefix = `[${partition} | ${message.offset}] `
            console.log(`-> ${prefix} | ${message.value.toString()}`)
        }
    });
};
run();
``` 

**Expected behavior**
The consumer has to consume the last 2 messages and commit offset as 3.

**Observed behavior**
The consumer will consume properly but it won't stop once it commits 3. It will go on to commit 4, then 5 indefinitely.

**Environment:**
 - OS: Mac OS 11.6
 - KafkaJS version 1.15.0
 - Platform: Microsoft Event Hubs
 - NodeJS version 12.13.0

**Additional context**
When [broker.fetch](https://github.com/tulios/kafkajs/blob/21571460be837c6aab78685d9910331ab7f0a645/src/consumer/consumerGroup.js#L488) returns results with offsets less than fetchOffset, then [isEmptyDueToLogCompactedMessages](https://github.com/tulios/kafkajs/blob/21571460be837c6aab78685d9910331ab7f0a645/src/consumer/consumerGroup.js#L542) becomes true. So, [resolveOffset](https://github.com/tulios/kafkajs/blob/21571460be837c6aab78685d9910331ab7f0a645/src/consumer/consumerGroup.js#L543) is called with [fetchedOffset](https://github.com/tulios/kafkajs/blob/21571460be837c6aab78685d9910331ab7f0a645/src/consumer/batch.js#L70) which increments the consumer group committed offset when [autoCommitOffsets](https://github.com/tulios/kafkajs/blob/21571460be837c6aab78685d9910331ab7f0a645/src/consumer/runner.js#L366) is called. And this happens indefinitely.

**Comment by nt-ijlizarralde** [comment] 2021-12-02 12:38
Hi, we've been with a similar issue since mid October. It seems related with an evolution on Azure Event Hubs that causes a race condition with KafkaJS. It's supposed to be fixed now, if not check with MSFT.

Here you have the explanation of Azure Team:

_As part of the service upgrade, a change was introduced to address a problem with regard to slow partition fetch for empty partition. However as part of the optimization, a changed behaviour is introduced. Specifically, normally, when client fetch for an offset that is in the future (i.e. one that exceeded the last known offset) the fetch call should return empty records. The changed behaviour caused a race condition, where in specific sequence, the last event will be returned instead of empty record.
 
The condition by itself, even though is undesirable, does not cause a permanent stuck condition, because normally a client would have ignored the redundant event, and ask for the same offset again, and eventually, the future offset will become current (because producer keep on sending events). However it looks like KafkaJS library has a specific behaviour where it does not detect that the event returned are in the past, and the client side in-memory offset just keep on incrementing (i.e. it blindly assume that if there are non-empty records, that records must have the offset that it asked for). This condition caused a permanent stuck issue under the right condition, because no matter how many events producer sends, the client will just keep on incrementing and asking for a larger and larger offset. This condition can only get resolved by restarting the client, wiping the in memory state of the offset and start from fresh.
 
The changed behaviour has been reverted for all public cluster, and the fix for the original problem will be fixed in such a way that will not cause further regression. Additional work items are planned to increase coverage for KafkaJS library to avoid hitting regression again in that category of external libraries._

**Closed** 2022-02-08 14:20 UTC
