### ISSUE TITLE
Invalid message without value for topic

### ISSUE THREAD

**Issue by vuongtt-bda** [tulios/kafkajs#1178] opened 2021-09-01 00:46 UTC
**Describe the bug**
When i send message:

```js
await producer.send({
  topic: 'topic',
  messages: [{
    key: 'key-1',
    value: JSON.stringify({some: 3})
  }]
})
```

**Expected behavior**
Successfully: send message

**Observed behavior**
"Invalid message without value for topic"

**Environment:**
 - OS: Ubuntu 20.04
 - KafkaJS version 1.15.0
 - Kafka version [e.g. 2.3.1]
 - NodeJS version 14.17.6

**Comment by buffaloDeveloper** [comment] 2021-12-22 03:58
Seeming the same error.

**Comment by Nevon** [comment] 2021-12-22 10:02
I wrote a test doing exactly that, and it passes just fine: https://github.com/tulios/kafkajs/blob/8d14f099d7077e8757fa72da4b8b2511b34caf04/src/producer/index.spec.js#L413-L434

It's far more likely that the object you're passing into `JSON.stringify` is undefined, so you're passing undefined as a value, since that's exactly what the code that triggers that error checks for. https://github.com/tulios/kafkajs/blob/d8fd93e7ce8e4675e3bb9b13d7a1e55a1e0f6bbf/src/producer/messageProducer.js#L72-L79

Closing as not reproducible.

**Closed by Nevon** 2021-12-22 10:02 UTC
