### ISSUE TITLE
Slow response/ Garbage data

### ISSUE THREAD

**Issue by kks010** [tulios/kafkajs#826] opened 2020-07-30 07:32 UTC
**Describe the bug**
We are facing issues with the slow response after a few days in our Kubernetes pod microservice which is the gateway used to request the response from different microservices within the AKS.

**To Reproduce**
Using the codebase, when an API call is made, then the gateway service acts as a request which subscribes to the topic, and then, on the other hand, we have other services listening continuously. When any request is made then they reply to the same and unsubscribe from the topic.
It works well and after a few days(10-12). The response from the other service is delayed and we have to restart the pods of the gateway service in other to fix the issue. 

**Expected behavior**
It should not be required to restart the pod and clear the garbage of the pod. 

**Observed behavior**
error log - 

ERROR: api-gateway-service/1 : {"level":"ERROR","timestamp":"2020-07-30T03:12:05.709Z","logger":"kafkajs","message":"[Connection] Connection error: write EPIPE","broker":"kafka-0.kafka.default.svc.cluster.local:9092","clientId":"plus1connect","stack":"Error: write EPIPE\n    at afterWriteDispatched (internal/stream_base_commons.js:150:25)\n    at writeGeneric (internal/stream_base_commons.js:141:3)\n    at Socket._writeGeneric (net.js:770:11)\n    at Socket._write (net.js:782:8)\n    at doWrite (_stream_writable.js:431:12)\n    at writeOrBuffer (_stream_writable.js:415:5)\n    at Socket.Writable.write (_stream_writable.js:305:11)\n    at Object.sendRequest (/usr/src/app/node_modules/kafkajs/src/network/connection.js:294:27)\n    at SocketRequest.send [as sendRequest] (/usr/src/app/node_modules/kafkajs/src/network/requestQueue/index.js:76:23)\n    at SocketRequest.send (/usr/src/app/node_modules/kafkajs/src/network/requestQueue/socketRequest.js:88:10)\n    at RequestQueue.push (/usr/src/app/node_modules/kafkajs/src/network/requestQueue/index.js:103:19)\n    at /usr/src/app/node_modules/kafkajs/src/network/connection.js:289:29\n    at new Promise (<anonymous>)\n    at sendRequest (/usr/src/app/node_modules/kafkajs/src/network/connection.js:284:14)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Connection.send (/usr/src/app/node_modules/kafkajs/src/network/connection.js:303:53)\n    at async Broker.metadata (/usr/src/app/node_modules/kafkajs/src/broker/index.js:189:12)\n    at async /usr/src/app/node_modules/kafkajs/src/cluster/brokerPool.js:127:25"}
--

**Environment:**
 - OS - ubuntu
 - KafkaJS version - 1.12.0
 - NodeJS version - 12.13

**Comment by goriunov** [comment] 2020-07-30 08:10
I doubt that it is kafkajs issue... underneath kafkajs uses node tcp to communicate. There are few reasons why you can get EPIPE one of them my be due to too large data check if you by any chance you are increasing message size and after reboot it just resets to default value

**Comment by kks010** [comment] 2020-07-30 08:57
I still feel that there are issues with accumulated garbage as I have read that Kafka does not have auto-delete of topics or some scripts which will cleanup old topics. 
So, whenever I restart the pods, it starts and serves as fresh topic in the group.

**Comment by ankon** [comment] 2020-07-30 11:50
You need to be a bit more precise here.

> I still feel that there are issues with accumulated garbage [...]

Are you refering to garbage in your program (potentially caused by issues in your code and/or libraries such as KafkaJS you're using)?

> [...] I have read that Kafka does not have auto-delete of topics or some scripts which will cleanup old topics.

... or are you now talking about the Kafka _brokers_ not doing what you want them to do? In that case you obviously need to start looking for issues there. FWIW: Kafka does provide controls to define when and how to expire messages in topics.

> So, whenever I restart the pods, it starts and serves as fresh topic in the group.

I'm actually assuming "the pods on which my clients are running", based on the initial description.

You didn't describe how your clients are configured (for example, are they comitting offsets? What's the offset reset configuration, or the `fromBeginning` value in KafkaJS; see https://kafka.js.org/docs/consuming for what's possible). What you did describe is that you seem to be subscribing/unsubscribing frequently in some clients, while not doing that in others. Do you see the problems in both types of clients?

You can investigate memory usage/garbage using a profiler, in your case probably by taking heap snapshots once in a while, and checking how the memory usage changes. For example, we use the [heapdump library](https://www.npmjs.com/package/heapdump) in our services, and can request a heapdump through a debug API call. We then have the Chrome DevTools which can compare two dumps against each other to highlight differences.

**Comment by kks010** [comment] 2020-07-30 13:09
Hi, 

Yes, I like the method of having snapshots of heap which I already had in mind to integrate.  I will integrate that.

Also, Yes, I am  ```referring to garbage in your program (potentially caused by libraries such as KafkaJS )?```

**Comment by Nevon** [comment] 2022-07-26 12:15
Closing this, as it is almost certainly a memory leak in the application itself, and there's no more information available.

**Closed by Nevon** 2022-07-26 12:15 UTC
