### ISSUE TITLE
Consuming messages by timestamp

### ISSUE THREAD

**Issue by Elhen15** [tulios/kafkajs#728] opened 2020-05-22 09:32 UTC
**Is your feature request related to a problem? Please describe.**
I have a consumer that needs to consume messages by timestamp.

**Describe the solution you'd like**
From kafka version 0.10.0 or higher, it's available to consume messages with getOffsetsByTimes method.

**Additional context**
Same issue on rd-kafka module https://github.com/Blizzard/node-rdkafka/issues/336

**Comment by Nevon** [comment] 2020-06-03 08:02
I believe this is a duplicate of #329, with a partially implemented PR #604. The idea would be to combine getting the offsets by timestamp via the admin API and then setting the consumer group offsets before consuming.

**Closed by Nevon** 2020-06-03 08:02 UTC

**Comment by Elhen15** [comment] 2020-06-03 18:44
Thanks for your answer! 
This is exactly what I've meant for, can you tell when the PR will be closed?
