### ISSUE TITLE
Subscribe a consumer with Partition Number

### ISSUE THREAD

**Issue by rajjagani021** [tulios/kafkajs#548] opened 2019-11-07 13:56 UTC
While producing a message we have facility that we can pass the partition number like below and it will produce the message to that partition.

```
const messages = [
    { key: 'key6', value: 'hello world 6', partition: 1 }, // send message in particular partition
];
```

but do we have any method on the consumer side, so we can subscribe to a consumer with the topic and partition number both? I have tried the below things but it's not working

```
       await consumer.subscribe({ 
            topic: topic_name, 
            fromBeginning: true,
            partition:0
        });
```

**Comment by ankon** [comment] 2019-11-07 14:58
I guess this is a duplicate of #373

**Comment by Nevon** [comment] 2019-11-08 15:52
Indeed. I'm closing this as a duplicate of #373.

**Closed by Nevon** 2019-11-08 15:52 UTC
Labels: duplicate
