### ISSUE TITLE
 KafkaJS to have built-in support for the Kerberos authentication

### ISSUE THREAD

**Issue by Vidz51** [tulios/kafkajs#865] opened 2020-09-11 11:40 UTC
Not able to use kafkajs as I need SASL authentication using kerberos.

Expeceted:  KafkaJS to have built-in support for the Kerberos authentication

**Comment by Nevon** [comment] 2020-09-11 11:43
GSSAPI authentication would not be built in to KafkaJS itself, as it requires native dependencies, but it would be possible to build it as a separate plugin, similar to how we support multiple compression codecs. #840 already details this issue, so I'm gonna close this issue as a duplicate of that one.

**Closed by Nevon** 2020-09-11 11:43 UTC
