### ISSUE TITLE
Consumers constantly get stuck

### ISSUE THREAD

**Issue by fenichelar** [tulios/kafkajs#1140] opened 2021-06-30 21:30 UTC
I am seeing my consumers constantly (every few minutes) get stuck processing messages. The consumer group rebalances to remove the stuck consumer, and then rebalances again to add the stuck consumer back to the group. I am using `kafkajs@v1.14.0`. There are no meaningful log messages, even at DEBUG level. The only ERROR level logs are `The group is rebalancing, so a rejoin is needed` which makes sense given the consumer group is spending a large percentage of the time rebalancing.

This is what my consumer looks like:

```js
const s3 = new aws.S3();
s3.config.update({
  maxRetries: 3,
  retryDelayOptions: {
    customBackoff: count => {
      return 100 * (Math.pow(2, count) - 1);
    },
  },
});

const kafkaClient = new kafka.Kafka({
  clientId: 'xxx',
  brokers: [
    'xxx',
    'xxx',
    'xxx',
    'xxx',
    'xxx',
  ],
  logLevel: kafka.logLevel.DEBUG,
});
const kafkaConsumer = kafkaClient.consumer({
  allowAutoTopicCreation: false,
  groupId: 'xxx',
  sessionTimeout: 60 * 1000,
  heartbeatInterval: 5 * 1000,
  maxBytesPerPartition: 3 * 1000 * 1000,
  maxBytes: 15 * 1000 * 1000,
});

await kafkaConsumer.connect();
await kafkaConsumer.subscribe({
  topic: 'xxxxx',
  fromBeginning: true,
});
await kafkaConsumer.run({
  partitionsConsumedConcurrently: Number.MAX_SAFE_INTEGER,
  eachBatchAutoResolve: false,
  autoCommitInterval: 5 * 1000,
  autoCommitThreshold: 25,
  eachBatch: async ({ batch, isRunning, isStale, heartbeat, resolveOffset, commitOffsetsIfNecessary }) => {
    const chunks = _.chunk(batch.messages, 25);
    for (const chunk of chunks) {
      if (!isRunning() || isStale()) {
        break;
      }
      await Promise.all(chunk.map(async message => {
        await s3.putObject({
          Bucket: 'xxx',
          Key: message.key,
          Body: message.value,
        }).promise();
      }));
      resolveOffset(chunk[chunk.length - 1].offset);
      await heartbeat();
      await commitOffsetsIfNecessary();
    }
  },
});
```

It is pretty simple. The critical thing to note is that multiple messages are processed in parallel within a batch. Processing message sequentially is not an option given the volume of messages and the inherent network latency associated with putting an object into S3.

I have tried a few other versions of the consumer and always see the same behavior:

```js
await kafkaConsumer.run({
  partitionsConsumedConcurrently: Number.MAX_SAFE_INTEGER,
  eachBatch: async ({ batch, heartbeat }) => {
    await Promise.all(batch.messages.map(async message => {
      await s3.putObject({
        Bucket: 'xxx',
        Key: `message.key,
        Body: message.value,
      }).promise();
      await heartbeat();
    }));
  },
});
```

```js
await kafkaConsumer.run({
  partitionsConsumedConcurrently: Number.MAX_SAFE_INTEGER,
  eachBatch: async ({ batch }) => {
    await Promise.all(batch.messages.map(async message => {
      await s3.putObject({
        Bucket: 'xxx',
        Key: `message.key,
        Body: message.value,
      }).promise();
    }));
  },
});
```

I have also tried a range of different values for `maxBytesPerPartition` and there was no change.

For completeness, there are 15 partitions, 5 brokers, and 5 consumers. The messages sizes range from 2 - 15 KB.

Any ideas on how I can diagnose why the consumers keep getting stuck?

**Comment by tulios** [comment] 2021-07-01 08:25
@fenichelar I see some red flags here:
> I am seeing my consumers constantly (every few minutes) get stuck processing messages
`partitionsConsumedConcurrently` defines how many partitions, not messages, are processed concurrently. By setting it to `Number.MAX_SAFE_INTEGER` you are saying that every partition fetched by the consumer should be processed in parallel. Then, I like that you are processing the messages within the partitions in chunks (`_.chunk(batch.messages, 25);`), but you are potentially generating ~400 promises which might be affecting the overall performance.

One suggestion here is to also make sure you heartbeat within each `s3.putObject`, it will only perform a heartbeat if it's necessary.

```diff
    await Promise.all(chunk.map(async message => {
        await s3.putObject({
          Bucket: 'xxx',
          Key: message.key,
          Body: message.value,
        }).promise();
+      await heartbeat();
    }));
```

>  sessionTimeout: 60 * 1000,
>  heartbeatInterval: 5 * 1000,

These numbers look too small for the amount of operations you are performing, I would bump `sessionTimeout` to 3 minutes and `heartbeatInterval` to 1/3 of that.

**Comment by fenichelar** [comment] 2021-07-01 14:39
Hello @tulios. Thanks for getting back to me so quickly.

I made the suggested changes:

1. Moved the heartbeat to be within the parallel processing function
2. Increased the `sessionTimeout` to 180000
3. Increased `heartbeatInterval` to 60000

I am still seeing the same issue. The only difference is that the consumer gets stuck for longer before the rebalancing occurs.

I should have mentioned this before, the consumer lag grows for every partition being processed by the consumer, not just one. So the entire consumer is stuck, not just one partition of the consumer. Because of this, I am thinking that there is something going on with the connection, but there aren't any log messages indicating connection issues (or any issues). I am using both SSL (one-way) and SASL.

**Comment by tulios** [comment] 2021-07-01 14:47
We need more data to properly debug this, can you measure and log how long does it take to process each chunk, something like:

```js
logger.info(`Processing chunk ${x} of ${y} chunks`);
const startAt = Date.now();
await Promise.all(chunk.map(async message => {
   const messageStartAt = Date.now();
    await s3.putObject({
      Bucket: 'xxx',
      Key: message.key,
      Body: message.value,
    }).promise();
   await heartbeat();
  logger.info(`Processed offset ${message.offset}, duration: ${Date.now() - messageStartAt}ms`);
}));
logger.info(`Processed chunk ${x}, duration: ${Date.now() - startAt}`);
```

my theory is that the event loop is getting blocked and this is taking a while, it would be nice to get a rough understanding of how long does it take to process each message and how long does it take to process the chunk.

**Comment by fenichelar** [comment] 2021-07-01 17:37
@tulios I'm working on rolling this out to production.

In the mean time, I rolled this out to the lab. The lab only has one partition and one consumer. The lab is also not in AWS, so latencies to S3 are likely higher than they would be in production (which is in AWS). I turned off the consumer, put 10,000 messages in the lab to process, and then turned on the consumer.

There were 15 batches.

There were 409 chunks. Min processing time: 193 ms. Max processing time: 1,472. Average processing time: 282 ms.

There were 10,000 offsets. Min processing time: 142 ms. Max processing time: 1,467. Average processing time: 198 ms.

**Comment by fenichelar** [comment] 2021-07-01 18:07
@tulios I don't want to speak too soon, but I think I figured it out!! The S3 SDK doesn't reuse TCP connections by default, so the SDK was opening a new TCP connection (including TLS handshake) for every PutObject request. I set the environmental variable `AWS_NODEJS_CONNECTION_REUSE_ENABLED` to `1` and I haven't seen any rebalances since. But it has only been a few minutes, so I need to let it run a little longer.

**Comment by fenichelar** [comment] 2021-07-01 18:50
@tulios It has been working for longer than it ever has. It appears the issue was that the TCP connections were occasionally taking forever to setup.

I'm tempted to remove the batch processing and put it back to just this:

```js
await kafkaConsumer.run({
  partitionsConsumedConcurrently: Number.MAX_SAFE_INTEGER,
  eachBatch: async ({ batch }) => {
    await Promise.all(batch.messages.map(async message => {
      await s3.putObject({
        Bucket: 'xxx',
        Key: `message.key,
        Body: message.value,
      }).promise();
    }));
  },
});
```

The code is much simpler and I suspect chunking the array is a fairly resource intensive operation given an individual message can be 15 kilobytes in size. I can use `maxBytesPerPartition` to adjust the number of simultaneous requests. Thoughts?

Also, what do you think about logging an error message in kafkajs if the `eachBatch` function doesn't execute within `sessionTimeout` to make it easier to diagnose this type of issue? Basically right before calling `eachBatch`, `setTimeout` would be invoked with a timeout of `sessionTimeout`. The function passed to `setTimeout` would simply log an error message. When `eachBatch` finishes executing, `setTimeout` would be cleared. I'm not very familiar with the internals of kafkajs, but I can try to put something together and submit a PR if you are interested. The logging could be enabled by a config option. Also, if the logging will be done at the debug level, then it could check the log level before executing `setTimeout` so that there aren't a bunch of useless timeouts created.

**Comment by tulios** [comment] 2021-07-02 12:06
@fenichelar the fix makes sense, it's usually "expensive" to create the connections all the time.

> I'm tempted to remove the batch processing and put it back to just this:

I would keep the chunks, I've seen so many times servers going crazy with unbound `Promise.all` calls, so I don't recommend that approach.

>  what do you think about logging an error message in kafkajs if the eachBatch function doesn't execute within sessionTimeout

I think it makes sense, there are logs about failures, etc. The problem is that you only know that you missed a heartbeat when you try to heartbeat and it fails and a local `setTimeout` might give you false positives.

I am closing the issue, but feel free to add more information here since this tend to be super useful in the future :D

**Closed by tulios** 2021-07-02 12:06 UTC
