### ISSUE TITLE
Unable to use CooperativeStickyAssignor

### ISSUE THREAD

**Issue by sethddigitile** [tulios/kafkajs#1189] opened 2021-09-16 20:30 UTC
**Describe the bug**
I am unable to use CooperativeStickyAssignor as my partitionAssigners value in setting my consumer configs

**To Reproduce**
const consumer = kafka.consumer({ groupId: process.env.KAFKA_GROUP_CONSUMER_ID, partitionAssigners: [PartitionAssigners.CooperativeStickyAssignor] });

**Expected behavior**
I expect to be able to set the CooperativeStickyAssignor as my partitionAssigner

**Comment by Nevon** [comment] 2022-03-09 10:17
This is a very strange way to pose a feature request. The only assigner KafkaJS provides out of the box is the RoundRobinAssigner. A cooperative assigner is just one part of implementing [KIP-429](https://cwiki.apache.org/confluence/display/KAFKA/KIP-429%3A+Kafka+Consumer+Incremental+Rebalance+Protocol).

Closing as a duplicate of #922

**Closed by Nevon** 2022-03-09 10:17 UTC
Labels: Feature request

**Comment by kagai** [comment] 2023-02-19 19:21
lets learn to be kind when doing feature requests, this are open source libraries and people invest time for free . Lets be respectful.

**Comment by RohanDoshi21** [comment] 2026-02-22 14:12
I have created an implementation and raised an PR. https://github.com/tulios/kafkajs/pull/1770

@Nevon @kagai Can you please take a look at this?
